In [9]:
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import os


In [1]:
import torch

In [ ]:
# visualize road network
def concat_files(path, final_file_name):
    '''
    Combines all files in a directory and saves it in a single file
    Parameters:
        path (str): directory where all independent files are saved
        final_file_name (str): path of the final file
    '''
    count = 0
    for file_name in os.listdir(path):
        if file_name.endswith('.csv'):
            try:
                df = pd.concat([df, pd.read_csv(path + file_name, low_memory=False)])
            except:
                df = pd.read_csv(path + file_name, low_memory=False)
            count += 1
    df = df.drop_duplicates().reset_index(drop=True)
    df.to_csv(final_file_name, index=False)



In [8]:
import torch

# load the adjacency matrix from a .pt file
adj_matrix = torch.load('CA-2/adj_matrix.pt')

/var/folders/sq/1nt0kg2x37j377lq7nqlpz4c0000gn/T/ipykernel_96276/3958096965.py:4: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  adj_matrix = torch.load('CA-2/adj_matrix.pt')

In [9]:

# assume adj_matrix is your sparse matrix
indices = adj_matrix._indices()
values = adj_matrix._values()

# number of edges
num_edges = values.shape[0]
print(f"Number of edges: {num_edges}")

# basic stats
print(f"Min value: {values.min().item()}, Max value: {values.max().item()}")

sample_indices = indices[:, :10]  # first 10 edges
sample_values = values[:10]
print("Sample edges (row, col):")
print(sample_indices)
print("Sample values:")
print(sample_values)
row_indices = indices[0, :]
col_indices = indices[1, :]

# degrees per node
# use torch.bincount for fast counting of occurrences
out_degrees = torch.bincount(row_indices, minlength=adj_matrix.size(0))
in_degrees = torch.bincount(col_indices, minlength=adj_matrix.size(1))

print(f"Average out-degree: {out_degrees.float().mean().item()}")
print(f"Average in-degree: {in_degrees.float().mean().item()}")

Number of edges: 5933931
Min value: 0.0, Max value: 112159.578125
Sample edges (row, col):
tensor([[  0,   1,   1,   2,   1,   0,   1, 184,   2,   1],
        [  1,   0,   2,   1,   0,   1, 184,   1,   1,   2]])
Sample values:
tensor([68.7080, 68.7080, 91.1300, 91.1300, 68.7080, 68.7080, 90.7430, 90.7430,
        91.1300, 91.1300])
Average out-degree: 4.774708271026611
Average in-degree: 4.774708271026611


In [10]:
edge_features = torch.load('/Users/beck/Documents/GitHub/cs-470-course-project/data/Edges/edge_features.pt')
print(edge_features)

/var/folders/sq/1nt0kg2x37j377lq7nqlpz4c0000gn/T/ipykernel_96276/1813186496.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  edge_features = torch.load('/Users/beck/Docum

{'oneway': tensor(indices=tensor([[      0,       1,       1,  ..., 1233998, 1234003,
                         793878],
                       [      1,       2,       0,  ..., 1234003, 1233998,
                         793745]]),
       values=tensor([0., 0., 0.,  ..., 0., 0., 0.]),
       size=(1242784, 1242784), nnz=3061644, layout=torch.sparse_coo), 'length': tensor(indices=tensor([[      0,       1,       1,  ..., 1233998, 1234003,
                         793878],
                       [      1,       2,       0,  ..., 1234003, 1233998,
                         793745]]),
       values=tensor([ 68.7080,  91.1300,  68.7080,  ..., 275.3920,
                      275.3920, 443.7310]),
       size=(1242784, 1242784), nnz=3061644, layout=torch.sparse_coo), 'bus_guideway': tensor(indices=tensor([[      0,       1,       1,  ..., 1233998, 1234003,
                         793878],
                       [      1,       2,       0,  ..., 1234003, 1233998,
                         793745

In [11]:

# assume adj_matrix is your sparse matrix
indices = adj_matrix._indices()
values = adj_matrix._values()

# number of edges
num_edges = values.shape[0]
print(f"Number of edges: {num_edges}")

# basic stats
print(f"Min value: {values.min().item()}, Max value: {values.max().item()}")

sample_indices = indices[:, :10]  # first 10 edges
sample_values = values[:10]
print("Sample edges (row, col):")
print(sample_indices)
print("Sample values:")
print(sample_values)
row_indices = indices[0, :]
col_indices = indices[1, :]

# degrees per node
# use torch.bincount for fast counting of occurrences
out_degrees = torch.bincount(row_indices, minlength=adj_matrix.size(0))
in_degrees = torch.bincount(col_indices, minlength=adj_matrix.size(1))

print(f"Average out-degree: {out_degrees.float().mean().item()}")
print(f"Average in-degree: {in_degrees.float().mean().item()}")

Number of edges: 5933931
Min value: 0.0, Max value: 112159.578125
Sample edges (row, col):
tensor([[  0,   1,   1,   2,   1,   0,   1, 184,   2,   1],
        [  1,   0,   2,   1,   0,   1, 184,   1,   1,   2]])
Sample values:
tensor([68.7080, 68.7080, 91.1300, 91.1300, 68.7080, 68.7080, 90.7430, 90.7430,
        91.1300, 91.1300])
Average out-degree: 4.774708271026611
Average in-degree: 4.774708271026611


In [ ]:
import pydeck

"""
HexagonLayer
==============

Personal injury road accidents in GB from 1979.

The layer aggregates data within the boundary of each hexagon cell.

This example is adapted from the deck.gl documentation.
"""

import pydeck as pdk

HEXAGON_LAYER_DATA = (
    "https://raw.githubusercontent.com/visgl/deck.gl-data/master/examples/3d-heatmap/heatmap-data.csv"  # noqa
)

# Define a layer to display on a map
layer = pdk.Layer(
    "HexagonLayer",
    HEXAGON_LAYER_DATA,
    get_position=["lng", "lat"],
    auto_highlight=True,
    elevation_scale=50,
    pickable=True,
    elevation_range=[0, 3000],
    extruded=True,
    coverage=1,
)

# Set the viewport location
view_state = pdk.ViewState(
    longitude=-1.415,
    latitude=52.2323,
    zoom=6,
    min_zoom=5,
    max_zoom=15,
    pitch=40.5,
    bearing=-27.36,
)

# Render
r = pdk.Deck(layers=[layer], initial_view_state=view_state)
r.to_html("hexagon_layer.html")


